---
deployment:
  tasks:
    - export DEPLOYPATH=/home/intermed/news.intermediacolombia.com/
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/cp -R inc $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R vendor $DEPLOYPATH
    - /bin/cp -R style.css $DEPLOYPATH
    - echo "✅ Despliegue completado en $DEPLOYPATH el $(date)"

	
